name: session_buddy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.2
  percent_indicator: ^4.2.4
  intl: ^0.20.2
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  firebase_dynamic_links: ^6.1.4
  uuid: ^4.5.1
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

flutter_icons:
  android: true               # Enable icon generation for Android
  ios: true                   # Enable icon generation for iOS
  image_path: "assets/icon.png"  # Path to your icon image
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#A2B7B7BB"