// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAarsskcs-veBfJg7b7Ff8xBfaDA2eebc',
    appId: '1:496802628827:android:973d9ab7b3df26f49a38fe',
    messagingSenderId: '496802628827',
    projectId: 'session-buddy-79d6e',
    storageBucket: 'session-buddy-79d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG7d1ldU2cr2QCpI-YemflqLkJ1ryaDxc',
    appId: '1:496802628827:ios:b2dc73798dd2d9569a38fe',
    messagingSenderId: '496802628827',
    projectId: 'session-buddy-79d6e',
    storageBucket: 'session-buddy-79d6e.firebasestorage.app',
    iosBundleId: 'com.example.sessionBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUPEbRl12kzYowWWYHzSkNTMzmdVxH1T4',
    appId: '1:897095720642:web:6fd8d89fc1353fad1be55b',
    messagingSenderId: '897095720642',
    projectId: 'session-buddy',
    authDomain: 'session-buddy.firebaseapp.com',
    storageBucket: 'session-buddy.firebasestorage.app',
    measurementId: 'G-4EC8PK4T2X',
  );
}